# Data cleaning

## Column Renames
- `institutions_distinct_count` → `authorship_count`
  - Reason: column counts author-institution pairs, not distinct institutions
  - Date: [today]
  - Action needed on next pull: either rename incoming column or pull true 
    distinct institution count via authorships[].institutions[].id

## Read csv

In [1]:
import pandas as pd

In [2]:
df_raw = pd.read_csv("../data/OpenAlex/openalex_ai_papers_full.csv")
df_raw.sample(20)

,id,title,publication_year,language,cited_by_count,referenced_works_count,fwci,institutions_distinct_count,countries_distinct_count,publication_type,...,authors_count,citation_top_1_percent,citation_top_10_percent,cited_by_percentile_year_min,cited_by_percentile_year_max,keyword_count,primary_topic_score,first_year_citations,topic_id,topic_name
288132,https://openalex.org/W4200407836,Solving the sparse QUBO on multiple GPUs for S...,2021,en,7,19,0.6990,9,0,proceedings-article,...,9,False,False,89.0,99.0,10,0.9999,1,T10682,Quantum Computing Algorithms and Architecture
26838,https://openalex.org/W2998148686,Torus Driving Mechanism with the Ability to Br...,2019,en,0,0,0.0000,8,1,journal-article,...,8,False,False,NaN,NaN,6,0.6092,0,T10181,Natural Language Processing Techniques
271738,https://openalex.org/W4404800755,KL-FedDis: A federated learning approach with ...,2024,en,9,24,3.2317,6,1,journal-article,...,6,False,True,98.0,99.0,6,1.0000,9,T10764,Privacy-Preserving Technologies in Data
60003,https://openalex.org/W2807181957,TIRAMISU Methodology for Semi-Automated Interp...,2016,en,1,0,0.4285,2,0,NaN,...,2,False,False,90.0,94.0,8,0.6447,0,T10320,Neural Networks and Applications
43922,https://openalex.org/W4386566860,Towards Speech to Speech Machine Translation f...,2023,en,10,18,1.7457,2,1,proceedings-article,...,2,False,False,97.0,98.0,13,0.9998,6,T10181,Natural Language Processing Techniques
46104,https://openalex.org/W4321243131,"Орчин цагийн солонгос хэлийг монгол, турк хэлт...",2023,en,0,4,0.0000,1,0,journal-article,...,1,False,False,NaN,NaN,10,0.9900,0,T10181,Natural Language Processing Techniques
967,https://openalex.org/W2963455036,Modeling Compositionality with Multiplicative ...,2015,en,13,0,1.7897,2,1,NaN,...,2,False,False,89.0,97.0,13,0.9986,3,T10181,Natural Language Processing Techniques
60649,https://openalex.org/W2542246449,Bio-inspired intelligent sensory processing wi...,2016,en,0,0,0.0000,3,0,NaN,...,3,False,False,NaN,NaN,7,0.9538,0,T10320,Neural Networks and Applications
140824,https://openalex.org/W4405009677,Explainable Supporting Facts Generation via Qu...,2024,en,0,0,0.0000,2,0,journal-article,...,2,False,False,NaN,NaN,10,0.9976,0,T10028,Topic Modeling
93576,https://openalex.org/W2242198393,More A than I: Why Artificial Intelligence Isn...,2015,en,1,21,0.4314,1,1,proceedings-article,...,1,False,False,90.0,94.0,10,0.9949,0,T10028,Topic Modeling
32762,https://openalex.org/W3110731112,Nuanciers - SVG - DarkOrchid,2020,fr,0,0,0.0000,1,0,NaN,...,1,False,False,NaN,NaN,3,0.9818,0,T10181,Natural Language Processing Techniques
1342,https://openalex.org/W2286804852,Punjabi Stemmer Using Punjabi WordNet Database,2015,en,10,12,0.8629,3,1,journal-article,...,3,False,False,89.0,96.0,7,0.9990,1,T10181,Natural Language Processing Techniques
232560,https://openalex.org/W2207826658,An efficient iterative algorithm for solving n...,2017,en,2,12,0.2075,2,1,journal-article,...,2,False,False,89.0,94.0,16,0.9627,1,T10100,Metaheuristic Optimization Algorithms Research
220175,https://openalex.org/W2526251947,Analyzing Behavior of Differential Drive Mobil...,2016,en,2,0,0.0000,2,0,journal-article,...,2,False,False,89.0,94.0,13,0.9194,0,T11975,Evolutionary Algorithms and Applications
12535,https://openalex.org/W2748439013,Uniform multilingualism: A media genealogy of ...,2017,en,11,74,0.3900,2,1,journal-article,...,2,False,False,89.0,97.0,9,0.9939,0,T10181,Natural Language Processing Techniques
264843,https://openalex.org/W4312840553,The DMA and the GDPR: Making Sense of Data Acc...,2022,en,2,0,NaN,1,1,journal-article,...,1,NaN,NaN,NaN,NaN,4,0.8134,0,T10764,Privacy-Preserving Technologies in Data
74903,https://openalex.org/W3044158726,Halfcentury long memory,2020,en,1,1,0.1326,1,0,journal-article,...,1,False,False,89.0,94.0,4,0.2600,0,T10320,Neural Networks and Applications
66973,https://openalex.org/W2901681643,Modeling of nonstationarity and long memory wi...,2018,en,1,18,0.1629,3,3,journal-article,...,3,False,False,90.0,94.0,7,0.9874,0,T10320,Neural Networks and Applications
49418,https://openalex.org/W4415797166,A Tractable Inference Perspective of Offline RL,2024,NaN,1,0,0.3667,4,0,proceedings-article,...,4,False,False,97.0,99.0,0,0.0691,0,T10181,Natural Language Processing Techniques
41503,https://openalex.org/W4385573977,Unbiased and Efficient Sampling of Dependency ...,2022,en,1,39,0.1326,1,0,proceedings-article,...,1,False,False,89.0,94.0,18,0.9822,1,T10181,Natural Language Processing Techniques

In [3]:
print(f"Shape: {df_raw.shape}")
print(f"Years: {df_raw['publication_year'].min()} – {df_raw['publication_year'].max()}")
print(f"Topics: {df_raw['topic_name'].nunique()}")

Shape: (301406, 22)
Years: 2015 – 2024
Topics: 10

In [4]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301406 entries, 0 to 301405
Data columns (total 22 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   id                            301406 non-null  object
 1   title                         301263 non-null  object
 2   publication_year              301406 non-null  int64
 3   language                      298519 non-null  object
 4   cited_by_count                301406 non-null  int64
 5   referenced_works_count        301406 non-null  int64
 6   fwci                          295292 non-null  float64
 7   institutions_distinct_count   301406 non-null  int64
 8   countries_distinct_count      301406 non-null  int64
 9   publication_type              265754 non-null  object
 10  is_oa                         301406 non-null  bool
 11  oa_status                     301406 non-null  object
 12  authors_count                 301406 non-null  int64
 13  citation_top_1_percent        295292 non-null  object
 14  citation_top_10_percent       295292 non-null  object
 15  cited_by_percentile_year_min  206629 non-null  float64
 16  cited_by_percentile_year_max  206629 non-null  float64
 17  keyword_count                 301406 non-null  int64
 18  primary_topic_score           301406 non-null  float64
 19  first_year_citations          301406 non-null  int64
 20  topic_id                      301406 non-null  object
 21  topic_name                    301406 non-null  object
dtypes: bool(1), float64(4), int64(8), object(9)
memory usage: 48.6+ MB

## Clean Null Values

In [5]:
df_raw.isnull().sum()

id                                  0
title                             143
publication_year                    0
language                         2887
cited_by_count                      0
referenced_works_count              0
fwci                             6114
institutions_distinct_count         0
countries_distinct_count            0
publication_type                35652
is_oa                               0
oa_status                           0
authors_count                       0
citation_top_1_percent           6114
citation_top_10_percent          6114
cited_by_percentile_year_min    94777
cited_by_percentile_year_max    94777
keyword_count                       0
primary_topic_score                 0
first_year_citations                0
topic_id                            0
topic_name                          0
dtype: int64

There are null values in columns 'title', 'language', 'fwci', 'publication_type', 'citation_top_1_percent', 'citation_top_10_percent', 'cited_by_percentile_year_min', 'cited_by_percentile_year_max'

Our target is 'citation_top_10_percent', so we can drop all rows where this column is null
But first let's check waht is the distribution of the rows with null in years and topics compared to the distribution of full data

In [6]:
df_raw[df_raw['citation_top_10_percent'].isnull()][['publication_year', 'topic_name']].value_counts().sort_index()

publication_year  topic_name
2015              Anomaly Detection Techniques and Applications      19
                  Evolutionary Algorithms and Applications           17
                  Metaheuristic Optimization Algorithms Research      8
                  Natural Language Processing Techniques            109
                  Neural Networks and Applications                  107
                                                                   ...
2024              Privacy-Preserving Technologies in Data            48
                  Quantum Computing Algorithms and Architecture      40
                  Sentiment Analysis and Opinion Mining              31
                  Speech Recognition and Synthesis                   17
                  Topic Modeling                                     48
Name: count, Length: 100, dtype: int64

Let's make it visual in the chart

In [7]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

null_target = df_raw[df_raw['citation_top_10_percent'].isnull()]

year_full  = df_raw['publication_year'].value_counts().sort_index()
year_null  = null_target['publication_year'].value_counts().sort_index()

topic_full = df_raw['topic_name'].value_counts()
topic_null = null_target['topic_name'].value_counts()

# Chart 1 — by year
fig_year = go.Figure()
fig_year.add_trace(go.Bar(name='Full dataset',    x=year_full.index.astype(str), y=year_full.values,  marker_color='steelblue'))
fig_year.add_trace(go.Bar(name='Null target rows', x=year_null.index.astype(str), y=year_null.values, marker_color='coral'))
fig_year.update_layout(barmode='group', title='Distribution by year', xaxis_title='Year', yaxis_title='Count', height=400)
fig_year.show()

# Chart 2 — by topic
fig_topic = go.Figure()
fig_topic.add_trace(go.Bar(name='Full dataset',    x=topic_full.values, y=topic_full.index, orientation='h', marker_color='steelblue'))
fig_topic.add_trace(go.Bar(name='Null target rows', x=topic_null.values, y=topic_null.index, orientation='h', marker_color='coral'))
fig_topic.update_layout(barmode='group', title='Distribution by topic', xaxis_title='Count', height=500)
fig_topic.show()

We can see that the distribution of the rows with null values in our target column 'citation_top_10_percent' is relatevily equal through the topics and years, so we can drop these rows.

In [8]:
df = df_raw.dropna(subset=['citation_top_10_percent']).copy()
print(f"Dropped {len(df_raw) - len(df):,} rows. Remaining: {len(df):,}")

Dropped 6,114 rows. Remaining: 295,292

Checking for null values after dropping the rows

In [9]:
df.isnull().sum()

id                                  0
title                             126
publication_year                    0
language                         2877
cited_by_count                      0
referenced_works_count              0
fwci                                0
institutions_distinct_count         0
countries_distinct_count            0
publication_type                34816
is_oa                               0
oa_status                           0
authors_count                       0
citation_top_1_percent              0
citation_top_10_percent             0
cited_by_percentile_year_min    88663
cited_by_percentile_year_max    88663
keyword_count                       0
primary_topic_score                 0
first_year_citations                0
topic_id                            0
topic_name                          0
dtype: int64

The biggest amount of nulls is in columns 'cited_by_percentile_year_min' and 'cited_by_percentile_year_max', it's almost 1/3 of the whole data.  
These columns are also not useful for the model bcause they are leaky and ill not be used as features.   
We can drop these two columns entirely, but first lets check their distribution through topics and years.

In [10]:
null_percentile = df[df['cited_by_percentile_year_min'].isnull() | df['cited_by_percentile_year_max'].isnull()]

year_full      = df['publication_year'].value_counts().sort_index()
year_null_perc = null_percentile['publication_year'].value_counts().sort_index()

topic_full      = df['topic_name'].value_counts()
topic_null_perc = null_percentile['topic_name'].value_counts()

# Chart 1 — by year
fig_year = go.Figure()
fig_year.add_trace(go.Bar(name='Full dataset',    x=year_full.index.astype(str),      y=year_full.values,      marker_color='steelblue'))
fig_year.add_trace(go.Bar(name='Null percentile', x=year_null_perc.index.astype(str), y=year_null_perc.values, marker_color='coral'))
fig_year.update_layout(barmode='group', title='Null in cited_by_percentile_year by year', xaxis_title='Year', yaxis_title='Count', height=400)
fig_year.show()

# Chart 2 — by topic
fig_topic = go.Figure()
fig_topic.add_trace(go.Bar(name='Full dataset',    x=topic_full.values,      y=topic_full.index,      orientation='h', marker_color='steelblue'))
fig_topic.add_trace(go.Bar(name='Null percentile', x=topic_null_perc.values, y=topic_null_perc.index, orientation='h', marker_color='coral'))
fig_topic.update_layout(barmode='group', title='Null in cited_by_percentile_year by topic', xaxis_title='Count', height=500)
fig_topic.show()

In [11]:
df['cited_by_percentile_year_min'].unique()

array([89., 97., 99., 90., 94., 96., 95., 98., 91., 93., nan])

In [12]:
df['cited_by_percentile_year_max'].unique()

array([100.,  99.,  98.,  97.,  96.,  95.,  94.,  93.,  nan])

The distribution of the null values is relatevelu equal - 25% of data in topics and years, this is a high volumne.  

We can drop these columns.

In [13]:
df_20 = df.drop(columns=['cited_by_percentile_year_min', 'cited_by_percentile_year_max'])
print(df_20.shape)

(295292, 20)

In [14]:
df_20.isnull().sum()

id                                 0
title                            126
publication_year                   0
language                        2877
cited_by_count                     0
referenced_works_count             0
fwci                               0
institutions_distinct_count        0
countries_distinct_count           0
publication_type               34816
is_oa                              0
oa_status                          0
authors_count                      0
citation_top_1_percent             0
citation_top_10_percent            0
keyword_count                      0
primary_topic_score                0
first_year_citations               0
topic_id                           0
topic_name                         0
dtype: int64

Now only 3 columns with nulls : tiltle 126, language 2877, publication_type 34816  

Let's check the distribution of missing publication_type through topics and years.

In [15]:
null_pub_type = df_20[df_20['publication_type'].isnull()]

year_full     = df_20['publication_year'].value_counts().sort_index()
year_null_pub = null_pub_type['publication_year'].value_counts().sort_index()

topic_full     = df_20['topic_name'].value_counts()
topic_null_pub = null_pub_type['topic_name'].value_counts()

# Chart 1 — by year
fig_year = go.Figure()
fig_year.add_trace(go.Bar(name='Full dataset',         x=year_full.index.astype(str),     y=year_full.values,     marker_color='steelblue'))
fig_year.add_trace(go.Bar(name='Null publication_type', x=year_null_pub.index.astype(str), y=year_null_pub.values, marker_color='coral'))
fig_year.update_layout(barmode='group', title='Null in publication_type by year', xaxis_title='Year', yaxis_title='Count', height=400)
fig_year.show()

# Chart 2 — by topic
fig_topic = go.Figure()
fig_topic.add_trace(go.Bar(name='Full dataset',         x=topic_full.values,     y=topic_full.index,     orientation='h', marker_color='steelblue'))
fig_topic.add_trace(go.Bar(name='Null publication_type', x=topic_null_pub.values, y=topic_null_pub.index, orientation='h', marker_color='coral'))
fig_topic.update_layout(barmode='group', title='Null in publication_type by topic', xaxis_title='Count', height=500)
fig_topic.show()

The missing values in publication_type are distributed rather equally through topics and years, except that is missing completely in years 2022-2024 which might indicate OpenAlex coverage issue for older years.  
Because this featue is valuable for the model - it indicates the type of article which influences the citation a lot - we will fill the nulls with 'unknown'

In [16]:
df_20['publication_type'] = df_20['publication_type'].fillna('unknown')

In [17]:
df_20.isnull().sum()

id                                0
title                           126
publication_year                  0
language                       2877
cited_by_count                    0
referenced_works_count            0
fwci                              0
institutions_distinct_count       0
countries_distinct_count          0
publication_type                  0
is_oa                             0
oa_status                         0
authors_count                     0
citation_top_1_percent            0
citation_top_10_percent           0
keyword_count                     0
primary_topic_score               0
first_year_citations              0
topic_id                          0
topic_name                        0
dtype: int64

Now we have two columns with nulls - title and language.  
Because this is a very little fraction of the whole data, we can fill those with 'unknown'

In [18]:
df_20['language'] = df_20['language'].fillna('unknown')
df_20['title']    = df_20['title'].fillna('unknown')

In [19]:
df_20.isnull().sum()

id                             0
title                          0
publication_year               0
language                       0
cited_by_count                 0
referenced_works_count         0
fwci                           0
institutions_distinct_count    0
countries_distinct_count       0
publication_type               0
is_oa                          0
oa_status                      0
authors_count                  0
citation_top_1_percent         0
citation_top_10_percent        0
keyword_count                  0
primary_topic_score            0
first_year_citations           0
topic_id                       0
topic_name                     0
dtype: int64

## Clean Duplicates

Let's check for duplicates

In [20]:
print(df_20.duplicated(subset=['id']).sum())

0

## Clean Datatypes

In [21]:
df_20.dtypes

id                              object
title                           object
publication_year                 int64
language                        object
cited_by_count                   int64
referenced_works_count           int64
fwci                           float64
institutions_distinct_count      int64
countries_distinct_count         int64
publication_type                object
is_oa                             bool
oa_status                       object
authors_count                    int64
citation_top_1_percent          object
citation_top_10_percent         object
keyword_count                    int64
primary_topic_score            float64
first_year_citations             int64
topic_id                        object
topic_name                      object
dtype: object

'citation_top_1_percent' and 'citation_top_10_percent' — currently object. These need to be converted to integers for the model, to create target variable.

'is_oa' — is bool, should be converted to int (0/1) for the model.

In [22]:
df_20['citation_top_1_percent']  = df_20['citation_top_1_percent'].map({'True': 1, 'False': 0, True: 1, False: 0}).astype('Int64')
df_20['citation_top_10_percent'] = df_20['citation_top_10_percent'].map({'True': 1, 'False': 0, True: 1, False: 0}).astype('Int64')
df_20['is_oa']                   = df_20['is_oa'].astype(int)

print(df_20.dtypes)

id                              object
title                           object
publication_year                 int64
language                        object
cited_by_count                   int64
referenced_works_count           int64
fwci                           float64
institutions_distinct_count      int64
countries_distinct_count         int64
publication_type                object
is_oa                            int64
oa_status                       object
authors_count                    int64
citation_top_1_percent           Int64
citation_top_10_percent          Int64
keyword_count                    int64
primary_topic_score            float64
first_year_citations             int64
topic_id                        object
topic_name                      object
dtype: object

In [23]:
df_20 = df_20.reset_index(drop=True)

In [24]:
df_20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295292 entries, 0 to 295291
Data columns (total 20 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           295292 non-null  object
 1   title                        295292 non-null  object
 2   publication_year             295292 non-null  int64
 3   language                     295292 non-null  object
 4   cited_by_count               295292 non-null  int64
 5   referenced_works_count       295292 non-null  int64
 6   fwci                         295292 non-null  float64
 7   institutions_distinct_count  295292 non-null  int64
 8   countries_distinct_count     295292 non-null  int64
 9   publication_type             295292 non-null  object
 10  is_oa                        295292 non-null  int64
 11  oa_status                    295292 non-null  object
 12  authors_count                295292 non-null  int64
 13  citation_top_1_percent       295292 non-null  Int64
 14  citation_top_10_percent      295292 non-null  Int64
 15  keyword_count                295292 non-null  int64
 16  primary_topic_score          295292 non-null  float64
 17  first_year_citations         295292 non-null  int64
 18  topic_id                     295292 non-null  object
 19  topic_name                   295292 non-null  object
dtypes: Int64(2), float64(2), int64(9), object(7)
memory usage: 45.6+ MB

## Checking unique values

In [25]:
df_20.columns.to_list()

['id',
 'title',
 'publication_year',
 'language',
 'cited_by_count',
 'referenced_works_count',
 'fwci',
 'institutions_distinct_count',
 'countries_distinct_count',
 'publication_type',
 'is_oa',
 'oa_status',
 'authors_count',
 'citation_top_1_percent',
 'citation_top_10_percent',
 'keyword_count',
 'primary_topic_score',
 'first_year_citations',
 'topic_id',
 'topic_name']

In [26]:
for col in df_20.columns:
    print(f"\n{col} ({df_20[col].nunique()} unique):")
    print(df_20[col].value_counts().head(20))
    print("-" * 50)

id (295292 unique):
id
https://openalex.org/W7134285326    1
https://openalex.org/W1902237438    1
https://openalex.org/W658020064     1
https://openalex.org/W2251135946    1
https://openalex.org/W1491002046    1
https://openalex.org/W2250342921    1
https://openalex.org/W2100664567    1
https://openalex.org/W1847618513    1
https://openalex.org/W1503259811    1
https://openalex.org/W2118434577    1
https://openalex.org/W2251743902    1
https://openalex.org/W2251329024    1
https://openalex.org/W2134036914    1
https://openalex.org/W2251622960    1
https://openalex.org/W2133458109    1
https://openalex.org/W2114719613    1
https://openalex.org/W3204406378    1
https://openalex.org/W2294774419    1
https://openalex.org/W1570098300    1
https://openalex.org/W2251324968    1
Name: count, dtype: int64
--------------------------------------------------

title (290624 unique):
title
unknown                                                                              126
IEEE Transactions on Information Theory publication information                      111
IEEE Transactions on Neural Networks and Learning Systems Information for Authors     68
IEEE Transactions on Neural Networks information for authors                          51
IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS publication information     48
IEEE Journal of Selected Topics in Quantum Electronics Topic Codes and Topics         46
Interval Methods in Knowledge Representation                                          46
IEEE/ACM Transactions on Audio, Speech, and Language Processing Edics                 42
Preface                                                                               41
IEEE Transactions on Evolutionary Computation information for authors                 41
IEEE Transactions on Evolutionary Computation Society Information                     40
IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS Publication Information     38
IEEE Transactions on Signal Processing Edics                                          36
IEEE Transactions on Evolutionary Computation publication information                 36
IEEE Journal of Selected Topics in Quantum Electronics                                34
IEEE Transactions on Neural Networks and Learning Systems Publication Information     30
Table of contents                                                                     26
Plain language summaries                                                              25
IEEE Transactions on Evolutionary Computation Publication Information                 23
Front Matter                                                                          22
Name: count, dtype: int64
--------------------------------------------------

publication_year (10 unique):
publication_year
2024    47184
2023    38653
2021    31548
2022    31519
2020    30064
2019    28046
2018    25116
2017    21623
2016    21461
2015    20078
Name: count, dtype: int64
--------------------------------------------------

language (78 unique):
language
en         281419
unknown      2877
fr           1928
pt           1246
es           1084
tr            997
ru            614
ko            561
de            507
hu            469
ja            431
zh            384
sv            307
nl            296
fi            279
ar            200
lv            159
et            146
pl            133
it            132
Name: count, dtype: int64
--------------------------------------------------

cited_by_count (993 unique):
cited_by_count
0     88467
1     34673
2     23606
3     17422
4     13871
5     11244
6      9194
7      7857
8      6664
9      5717
10     5022
11     4414
12     4044
13     3557
14     3238
15     2842
16     2655
17     2478
18     2250
19     1984
Name: count, dtype: int64
--------------------------------------------------

referenced_works_count (423 unique):
referenced_works_count
0     74790
15     5023
16     5021
17     4947
14     4912
20     4848
13     4834
18     4815
19     4785
12     4726
10     4688
23     4658
22     4612
21     4603
24     4556
11     4491
25     4435
26     4345
9      4250
28     4160
Name: count, dtype: int64
--------------------------------------------------

fwci (14003 unique):
fwci
0.0000    99166
0.1326     4393
0.1360     2588
0.1400     2459
0.3637     2342
0.1629     2292
0.2651     2142
0.1950     1941
0.1748     1940
0.4314     1857
0.4285     1840
0.2719     1718
0.2800     1632
0.3977     1629
0.3626     1601
0.1746     1263
0.3497     1250
0.3900     1231
0.4079     1228
0.7274     1214
Name: count, dtype: int64
--------------------------------------------------

institutions_distinct_count (170 unique):
institutions_distinct_count
3     63809
2     63367
4     48422
1     44926
5     31770
6     19995
7      8930
8      4481
0      2468
9      2332
10     1314
11      755
12      539
13      315
14      227
15      137
16      134
18       85
17       81
19       63
Name: count, dtype: int64
--------------------------------------------------

countries_distinct_count (22 unique):
countries_distinct_count
1     170527
0      76004
2      37908
3       7956
4       1995
5        554
6        188
7         66
8         36
9         16
12         8
10         8
11         6
18         5
13         4
14         2
16         2
17         2
30         2
22         1
Name: count, dtype: int64
--------------------------------------------------

publication_type (579 unique):
publication_type
journal-article                            128716
proceedings-article                        112687
unknown                                     34816
text                                         2399
article-journal                              2054
article                                      1633
info:eu-repo/semantics/article               1279
Conference papers                            1125
info:eu-repo/semantics/conferenceObject       846
info:eu-repo/semantics/publishedVersion       838
Text                                          701
Article                                       445
Student thesis                                444
book-chapter                                  285
posted-content                                232
InProceedings                                 232
Project                                       232
Conference or Workshop Item                   222
contributionToPeriodical                      216
info:eu-repo/semantics/other                  209
Name: count, dtype: int64
--------------------------------------------------

is_oa (2 unique):
is_oa
0    161713
1    133579
Name: count, dtype: int64
--------------------------------------------------

oa_status (6 unique):
oa_status
closed     161713
gold        51613
diamond     30175
green       27583
hybrid      13915
bronze      10293
Name: count, dtype: int64
--------------------------------------------------

authors_count (101 unique):
authors_count
3      63809
2      63367
4      48422
1      44926
5      31770
6      19995
7       8930
8       4481
0       2468
9       2332
10      1314
11       755
12       539
13       315
14       227
15       137
16       134
100      110
18        85
17        81
Name: count, dtype: int64
--------------------------------------------------

citation_top_1_percent (2 unique):
citation_top_1_percent
0    289582
1      5710
Name: count, dtype: Int64
--------------------------------------------------

citation_top_10_percent (2 unique):
citation_top_10_percent
0    242483
1     52809
Name: count, dtype: Int64
--------------------------------------------------

keyword_count (31 unique):
keyword_count
12    25767
11    25733
10    24315
13    24034
9     22542
14    21173
8     20690
7     18564
6     17045
15    17005
5     14596
16    12585
4     10898
17     8850
3      8462
18     5690
1      4771
2      4461
19     3477
20     2076
Name: count, dtype: int64
--------------------------------------------------

primary_topic_score (9592 unique):
primary_topic_score
0.9999    37767
1.0000    29841
0.9998    18574
0.9997    12178
0.9996     8814
0.9995     6957
0.9994     5830
0.9993     4807
0.9992     4273
0.9991     3700
0.9990     3296
0.9989     2947
0.9988     2743
0.9987     2465
0.9986     2284
0.9985     2130
0.9984     1994
0.9983     1795
0.9982     1730
0.9981     1689
Name: count, dtype: int64
--------------------------------------------------

first_year_citations (273 unique):
first_year_citations
0     147465
1      47111
2      26598
3      16768
4      11538
5       8357
6       6223
7       4868
8       3717
9       3094
10      2431
11      1973
12      1719
13      1423
14      1206
15      1037
16       952
17       782
18       682
19       572
Name: count, dtype: int64
--------------------------------------------------

topic_id (10 unique):
topic_id
T10181    54200
T10028    48841
T10320    35265
T11512    28283
T10764    27269
T10664    26121
T10682    24435
T10100    21472
T10201    21329
T11975     8077
Name: count, dtype: int64
--------------------------------------------------

topic_name (10 unique):
topic_name
Natural Language Processing Techniques            54200
Topic Modeling                                    48841
Neural Networks and Applications                  35265
Anomaly Detection Techniques and Applications     28283
Privacy-Preserving Technologies in Data           27269
Sentiment Analysis and Opinion Mining             26121
Quantum Computing Algorithms and Architecture     24435
Metaheuristic Optimization Algorithms Research    21472
Speech Recognition and Synthesis                  21329
Evolutionary Algorithms and Applications           8077
Name: count, dtype: int64
--------------------------------------------------

Looking at the data what we see:

title has many junk records
There are IEEE "publication information", "Table of contents", "Front Matter" type titles — these are not research papers, they're journal metadata records. Worth dropping.

publication_type — 579 unique values is a mess
What should be a clean categorical has fragmented into many variants of the same thing. Needs consolidating into a few clean categories.

countries_distinct_count — 76,004 rows with 0 countries
That's a lot. Worth investigating — likely papers where OpenAlex couldn't resolve any institution to a country.

authors_count — mirrors institutions_distinct_count exactly
Suspicious — they have identical value counts. Could be a data pull issue worth checking.

referenced_works_count — 74,790 rows with 0
That's 25% of papers with no references. Could be legitimate (some paper types don't have structured references in OpenAlex) but worth a quick look.

## Cleaning titles

### Duplicated titles

Let's check the duplicated rows in title, year, fwci, cited by count

In [27]:
duplicate_titles = df_20[df_20.duplicated(subset=['title'], keep=False)].sort_values('title')
print(f"Rows with duplicate titles: {len(duplicate_titles):,}")
print(f"Unique titles that repeat: {duplicate_titles['title'].nunique():,}")
duplicate_titles[['title', 'cited_by_count', 'fwci', 'publication_year', 'topic_name']]

Rows with duplicate titles: 7,858
Unique titles that repeat: 3,190

,title,cited_by_count,fwci,publication_year,topic_name
255718,&lt;i&gt;K&lt;/i&gt;-anonymity scheme for priv...,0,0.0000,2021,Privacy-Preserving Technologies in Data
255256,&lt;i&gt;K&lt;/i&gt;-anonymity scheme for priv...,4,0.4079,2021,Privacy-Preserving Technologies in Data
73541,(Invited) Binary Stochastic Neurons and Compou...,0,0.0000,2020,Neural Networks and Applications
78037,(Invited) Binary Stochastic Neurons and Compou...,0,0.0000,2021,Neural Networks and Applications
4902,12th Congress for Finno-Ugric Studies: Persona...,0,0.0000,2015,Natural Language Processing Techniques
...,...,...,...,...,...
227949,配電系統状態推定へのDifferential Evolutionary Particle S...,0,0.0000,2017,Metaheuristic Optimization Algorithms Research
234331,학술·연구정보가이드: Computer Science 분야 (03): Algorith...,0,0.0000,2020,Metaheuristic Optimization Algorithms Research
234546,학술·연구정보가이드: Computer Science 분야 (03): Algorith...,0,0.0000,2020,Metaheuristic Optimization Algorithms Research
74420,학술·연구정보가이드: Computer Science 분야 (03): Gaussian...,0,0.0000,2020,Neural Networks and Applications
73559,학술·연구정보가이드: Computer Science 분야 (03): Gaussian...,0,0.0000,2020,Neural Networks and Applications

Let's check what titles have same year, citation amount, fwci

In [28]:
exact_dupes = df_20.duplicated(subset=['title', 'publication_year', 'cited_by_count', 'fwci', 'topic_name'], keep=False)
print(f"Exact duplicates (title + year + citations): {exact_dupes.sum():,}")

Exact duplicates (title + year + citations): 2,932

In [29]:
df_20[exact_dupes].sort_values('title')[['id','title','publication_year', 'cited_by_count', 'fwci', 'topic_name']].head(10)

,id,title,publication_year,cited_by_count,fwci,topic_name
5300,https://openalex.org/W4300009002,12th Congress for Finno-Ugric Studies: Persona...,2015,0,0.0,Natural Language Processing Techniques
4902,https://openalex.org/W2987809845,12th Congress for Finno-Ugric Studies: Persona...,2015,0,0.0,Natural Language Processing Techniques
27090,https://openalex.org/W3197412964,13. Ulusal Yazılım Mühendisliği Sempozyumu,2019,0,0.0,Natural Language Processing Techniques
26347,https://openalex.org/W3006520634,13. Ulusal Yazılım Mühendisliği Sempozyumu,2019,0,0.0,Natural Language Processing Techniques
234605,https://openalex.org/W4251598402,2020 4th Conference on Swarm Intelligence and ...,2020,0,0.0,Metaheuristic Optimization Algorithms Research
234607,https://openalex.org/W4252153203,2020 4th Conference on Swarm Intelligence and ...,2020,0,0.0,Metaheuristic Optimization Algorithms Research
79941,https://openalex.org/W4286383371,3:1M: An Interpretable Dynamical AI Agent,2022,0,0.0,Neural Networks and Applications
80119,https://openalex.org/W4304459472,3:1M: An Interpretable Dynamical AI Agent,2022,0,0.0,Neural Networks and Applications
80123,https://openalex.org/W4306195409,3:1M: An Interpretable Dynamical AI Agent,2022,0,0.0,Neural Networks and Applications
79937,https://openalex.org/W4285832920,3:1M: An Interpretable Dynamical AI Agent,2022,0,0.0,Neural Networks and Applications

Dropping those rows with duplicated titles

In [30]:
df_20 = df_20.drop_duplicates(subset=['title', 'publication_year', 'cited_by_count'], keep='first').reset_index(drop=True)
print(f"Remaining rows: {len(df_20):,}")

Remaining rows: 293,298

### Junk titles

In [31]:
print(f"title ({df_20['title'].nunique()} unique):")
print(df_20['title'].value_counts().head(50))

title (290624 unique):
title
unknown                                                                                                                  91
IEEE Journal of Selected Topics in Quantum Electronics                                                                   29
Poster                                                                                                                   13
IEEE Journal of Selected Topics in Quantum Electronics Topic Codes and Topics                                            13
Preface                                                                                                                  11
IEEE Transactions on Information Theory publication information                                                          10
Sentiment Analysis of Twitter Data                                                                                        9
IEEE Transactions on Evolutionary Computation Society Information                                                         9
IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS publication information                                         9
Interval Methods in Knowledge Representation                                                                              9
IEEE Transactions on Evolutionary Computation information for authors                                                     7
IEEE Transactions on Neural Networks and Learning Systems Information for Authors                                         7
IEEE Transactions on Evolutionary Computation publication information                                                     7
IEEE Transactions on Neural Networks and Learning Systems Publication Information                                         7
Natural Language Processing                                                                                               7
Announcement of the Neural Networks Best Paper Award                                                                      7
IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS Publication Information                                         7
Model-based evolutionary algorithms                                                                                       6
Representations for evolutionary algorithms                                                                               6
IEEE/ACM Transactions on Audio, Speech, and Language Processing Edics                                                     6
Front Matter                                                                                                              6
Table of Contents                                                                                                         6
Twitter Sentiment Analysis                                                                                                6
French language abstracts                                                                                                 6
Quantum Computing                                                                                                         6
Circuit Theory Based on New Concepts and Its Application to Quantum Theory                                                6
IEEE Transactions on Neural Networks information for authors                                                              6
TWITTER SENTIMENT ANALYSIS                                                                                                5
ICAI-CMA Snapshots                                                                                                        5
Journal of Global Faultlines                                                                                              5
Evolutionary computation and evolutionary deep learning for image analysis, signal processing and pattern recognition     5
IEEE Congress on Evolutionary Computation                                                                                 5
Automatic Text Summarization                                                                                              5
Evolution of neural networks                                                                                              5
Data and Syntax                                                                                                           5
CMA-ES and advanced adaptation mechanisms                                                                                 5
Book review                                                                                                               5
Evolutionary computation                                                                                                  5
Hyper-heuristics tutorial                                                                                                 5
Sumário Bilingue                                                                                                          5
Learning classifier systems                                                                                               5
Twitter Sentiment Analysis using Machine Learning                                                                         4
Pretrained Transformers for Text Ranking: BERT and Beyond                                                                 4
[Title page i]                                                                                                            4
Table of contents                                                                                                         4
A Survey on Sentiment Analysis                                                                                            4
Table of contents in English                                                                                              4
Introduction                                                                                                              4
Neural Machine Translation                                                                                                4
IEEE Journal of Selected Topics in Quantum Electronics Information for Authors                                            4
Name: count, dtype: int64

There are many strange titles that are probably not articles, let's try to catch them and drop
Such as 'Front Matter', 'Table of Contents'etc

In [32]:
junk_titles = [
    'Preface', 'Front Matter', 'Table of contents', 'Table of Contents',
    'information for authors',
    'Sumário Bilingue', 'Sumário bilingue', 'Summaries in Tamil', 'Summaries',
    'Foreword', 'Keynote', 'Tutorials', 'Final Program',
    'Message from the Chairs', 'Peer Review Statement', 'Book Review',
    'Book review', 'Editorial introduction',
    '[25 Years Ago]', 'Suunvuoro',
    'Table of contents in English',
    'ICAI-CMA Snapshots',
    'Hyper-heuristics tutorial', 'Summaries in Tamil',
    'Preface to the Special Issue on Theory of Genetic and Evolutionary Computation',
    'Announcement of the Neural Networks Best Paper Award',
    'French language abstracts', 'Editorial'
]

junk_patterns = [
    'publication information', 'Information for Authors',
    'Society Information',
    ' Edics$'  # only match Edics at end of title
]

mask_exact   = df_20['title'].isin(junk_titles)
mask_pattern = df_20['title'].str.contains('|'.join(junk_patterns), case=False, na=False, regex=True)

print(f"Exact matches:   {mask_exact.sum():,}")
print(f"Pattern matches: {mask_pattern.sum():,}")
print(f"Total to drop:   {(mask_exact | mask_pattern).sum():,}")

# Verify no false positives
df_20[mask_exact | mask_pattern][['title', 'cited_by_count', 'fwci']].sort_values('cited_by_count', ascending=False).head(20)

Exact matches:   112
Pattern matches: 116
Total to drop:   226

,title,cited_by_count,fwci
168958,Editorial,11,1.224400
287317,IEEE Journal of Selected Topics in Quantum Ele...,3,0.525400
75625,Announcement of the Neural Networks Best Paper...,2,0.271900
245189,Keynote,2,0.390000
64348,IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARN...,2,0.325800
75433,IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARN...,2,0.141104
58222,IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARN...,1,0.428500
58223,IEEE Transactions on Neural Networks informati...,1,0.000000
72069,IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARN...,1,0.000000
58225,IEEE Transactions on Signal Processing Edics,1,0.428500
3012,Summaries in Tamil,1,0.000000
284561,IEEE Journal of Selected Topics in Quantum Ele...,1,0.132600
214771,IEEE Transactions on Evolutionary Computation ...,1,0.000000
216640,Preface to the Special Issue on Theory of Gene...,1,0.144500
54722,IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARN...,1,0.000000
55233,[25 Years Ago],1,0.000000
72436,ICAI-CMA Snapshots,1,0.132600
63514,IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARN...,1,0.000000
75869,ICAI-CMA Snapshots,1,0.136000
78433,IEEE Transactions on Information Theory Public...,1,0.132600

In [33]:
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    print(df_20[mask_exact | mask_pattern][['title', 'cited_by_count', 'fwci', 'publication_year', 'topic_name']].sort_values('cited_by_count', ascending=False).to_string())

                                                                                                title  cited_by_count      fwci  publication_year                                      topic_name
168958                                                                                      Editorial              11  1.224400              2020           Sentiment Analysis and Opinion Mining
287317                 IEEE Journal of Selected Topics in Quantum Electronics Information for Authors               3  0.525400              2023   Quantum Computing Algorithms and Architecture
75625                                            Announcement of the Neural Networks Best Paper Award               2  0.271900              2021                Neural Networks and Applications
245189                                                                                        Keynote               2  0.390000              2017         Privacy-Preserving Technologies in Data
64348               IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS publication information               2  0.325800              2018                Neural Networks and Applications
75433               IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS Publication Information               2  0.141104              2021                Neural Networks and Applications
58222               IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS publication information               1  0.428500              2016                Neural Networks and Applications
58223                                    IEEE Transactions on Neural Networks information for authors               1  0.000000              2016                Neural Networks and Applications
72069               IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS Publication Information               1  0.000000              2020                Neural Networks and Applications
58225                                                    IEEE Transactions on Signal Processing Edics               1  0.428500              2016                Neural Networks and Applications
3012                                                                               Summaries in Tamil               1  0.000000              2015          Natural Language Processing Techniques
284561                                   IEEE Journal of Selected Topics in Quantum Electronics Edics               1  0.132600              2022   Quantum Computing Algorithms and Architecture
214771                              IEEE Transactions on Evolutionary Computation Society Information               1  0.000000              2017        Evolutionary Algorithms and Applications
216640                 Preface to the Special Issue on Theory of Genetic and Evolutionary Computation               1  0.144500              2019        Evolutionary Algorithms and Applications
54722               IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS publication information               1  0.000000              2015                Neural Networks and Applications
55233                                                                                  [25 Years Ago]               1  0.000000              2015                Neural Networks and Applications
72436                                                                              ICAI-CMA Snapshots               1  0.132600              2020                Neural Networks and Applications
63514               IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS publication information               1  0.000000              2018                Neural Networks and Applications
75869                                                                              ICAI-CMA Snapshots               1  0.136000              2021                Neural Networks and Applications
78433                                 IEEE Transactions on Information Theory Publication Information               1  0.132600              2022                Neural Networks and Applications
143906                          IEEE/ACM Transactions on Audio, Speech, and Language Processing Edics               1  0.162900              2018                Speech Recognition and Synthesis
138419                          IEEE/ACM Transactions on Audio, Speech, and Language Processing Edics               1  0.000000              2015                Speech Recognition and Synthesis
152016         IEEE/ACM Transactions on Audio, Speech and Language Processing Publication Information               1  0.132700              2022                Speech Recognition and Synthesis
214077                              IEEE Transactions on Evolutionary Computation Society Information               1  0.428500              2016        Evolutionary Algorithms and Applications
141800                          IEEE/ACM Transactions on Audio, Speech, and Language Processing EDICS               1  0.000000              2017                Speech Recognition and Synthesis
80930               IEEE Transactions on Neural Networks and Learning Systems Publication Information               1  0.174800              2023                Neural Networks and Applications
75498               IEEE Transactions on Neural Networks and Learning Systems Information for Authors               1  0.000000              2021                Neural Networks and Applications
75502               IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS Publication Information               1  0.000000              2021                Neural Networks and Applications
78703               IEEE Transactions on Neural Networks and Learning Systems Publication Information               1  0.132600              2022                Neural Networks and Applications
78691          IEEE Transactions on Pattern Analysis and Machine Intelligence Publication Information               1  0.132700              2022                Neural Networks and Applications
226098                                                                      Hyper-heuristics tutorial               1  0.103800              2017  Metaheuristic Optimization Algorithms Research
237284                                                                              Table of Contents               1  0.132600              2022  Metaheuristic Optimization Algorithms Research
216622                                                                                        Preface               1  0.000000              2019        Evolutionary Algorithms and Applications
216618                                                                         Editorial introduction               1  0.144600              2019        Evolutionary Algorithms and Applications
228121                                                                      Hyper-heuristics tutorial               1  0.000000              2018  Metaheuristic Optimization Algorithms Research
101789                                                                                    Book review               1  0.140000              2019                                  Topic Modeling
80978                                                                                     Book review               1  0.176600              2023                Neural Networks and Applications
40394                                                                       French language abstracts               0  0.000000              2022          Natural Language Processing Techniques
37154                                                                    Table of contents in English               0  0.000000              2021          Natural Language Processing Techniques
37142                                                                                Sumário Bilingue               0  0.000000              2021          Natural Language Processing Techniques
40329                                                                                       Summaries               0  0.000000              2022          Natural Language Processing Techniques
37246                                                                       French language abstracts               0  0.000000              2021          Natural Language Processing Techniques
40858                                                                                     Book Review               0  0.000000              2022          Natural Language Processing Techniques
32696                                                                                       Suunvuoro               0  0.000000              2020          Natural Language Processing Techniques
50461                                                                       French language abstracts               0  0.000000              2024          Natural Language Processing Techniques
45295                                                                                         Preface               0  0.000000              2023          Natural Language Processing Techniques
45578                                                                    Table of contents in English               0  0.000000              2023          Natural Language Processing Techniques
44924                                                                                       Summaries               0  0.000000              2023          Natural Language Processing Techniques
40918                                                                    Table of contents in English               0  0.000000              2022          Natural Language Processing Techniques
40921                                                                                Sumário Bilingue               0  0.000000              2022          Natural Language Processing Techniques
56645                                    IEEE Transactions on Neural Networks information for authors               0  0.000000              2015                Neural Networks and Applications
56642                                                                                         Preface               0  0.000000              2015                Neural Networks and Applications
56640                                                    IEEE Transactions on Signal Processing Edics               0  0.000000              2015                Neural Networks and Applications
56650               IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS publication information               0  0.000000              2015                Neural Networks and Applications
56653                                 IEEE Transactions on Information Theory publication information               0  0.000000              2015                Neural Networks and Applications
56652               IEEE Transactions on Neural Networks and Learning Systems publication information               0  0.000000              2015                Neural Networks and Applications
59818                                    IEEE Transactions on Neural Networks information for authors               0  0.000000              2016                Neural Networks and Applications
59825                                                                                       Spl Edics               0  0.000000              2016                Neural Networks and Applications
59826                                                    IEEE Transactions on Signal Processing Edics               0  0.000000              2016                Neural Networks and Applications
59831               IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS publication information               0  0.000000              2016                Neural Networks and Applications
59839                                 IEEE Transactions on Information Theory publication information               0  0.000000              2016                Neural Networks and Applications
46429                                                                                    Front Matter               0  0.000000              2023          Natural Language Processing Techniques
53397                                                                                    Front Matter               0  0.000000              2024          Natural Language Processing Techniques
45193                                                                           Peer Review Statement               0  0.000000              2023          Natural Language Processing Techniques
41620                                                                                    Front Matter               0  0.000000              2022          Natural Language Processing Techniques
44566                                                                       French language abstracts               0  0.000000              2023          Natural Language Processing Techniques
63001                                 IEEE Transactions on Information Theory publication information               0  0.000000              2017                Neural Networks and Applications
62989               IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS publication information               0  0.000000              2017                Neural Networks and Applications
62987                                                                               Table of contents               0  0.000000              2017                Neural Networks and Applications
62983                                    IEEE Transactions on Neural Networks information for authors               0  0.000000              2017                Neural Networks and Applications
62071                                            Announcement of the Neural Networks Best Paper Award               0  0.000000              2017                Neural Networks and Applications
66693                                 IEEE Transactions on Information Theory publication information               0  0.000000              2018                Neural Networks and Applications
32858                                                                                    Front Matter               0  0.000000              2020          Natural Language Processing Techniques
32726                                                                                         Preface               0  0.000000              2020          Natural Language Processing Techniques
32703                                                                                       Summaries               0  0.000000              2020          Natural Language Processing Techniques
5210                                                                                 Sumário bilingue               0  0.000000              2015          Natural Language Processing Techniques
5197                                                                               Summaries in Tamil               0  0.000000              2015          Natural Language Processing Techniques
10997                                                                                        Foreword               0  0.000000              2016          Natural Language Processing Techniques
11002                                                                              Summaries in Tamil               0  0.000000              2016          Natural Language Processing Techniques
11028                                                                                         Preface               0  0.000000              2016          Natural Language Processing Techniques
10990                                                                                Sumário bilingue               0  0.000000              2016          Natural Language Processing Techniques
21544                                                                                     Book review               0  0.000000              2018          Natural Language Processing Techniques
26987                                                                       French language abstracts               0  0.000000              2019          Natural Language Processing Techniques
27004                                                                                       Suunvuoro               0  0.000000              2019          Natural Language Processing Techniques
27130                                                                                    Front Matter               0  0.000000              2019          Natural Language Processing Techniques
32679                                                                    Table of contents in English               0  0.000000              2020          Natural Language Processing Techniques
32694                                                                                Sumário Bilingue               0  0.000000              2020          Natural Language Processing Techniques
32695                                                                       French language abstracts               0  0.000000              2020          Natural Language Processing Techniques
11115                                                                                    Front Matter               0  0.000000              2016          Natural Language Processing Techniques
16092                                                                                Sumário Bilingue               0  0.000000              2017          Natural Language Processing Techniques
16103                                                                                Sumário bilingue               0  0.000000              2017          Natural Language Processing Techniques
16105                                                                              Summaries in Tamil               0  0.000000              2017          Natural Language Processing Techniques
16108                                                                                        Foreword               0  0.000000              2017          Natural Language Processing Techniques
16119                                                                                         Preface               0  0.000000              2017          Natural Language Processing Techniques
21510                                                                                Sumário Bilingue               0  0.000000              2018          Natural Language Processing Techniques
21511                                                                                        Foreword               0  0.000000              2018          Natural Language Processing Techniques
21513                                                                                       Suunvuoro               0  0.000000              2018          Natural Language Processing Techniques
4587                                                                                      Book review               0  0.000000              2015          Natural Language Processing Techniques
74190               IEEE Transactions on Neural Networks and Learning Systems Information for Authors               0  0.000000              2020                Neural Networks and Applications
74185               IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS Publication Information               0  0.000000              2020                Neural Networks and Applications
74175                      IEEE Journal on Special Areas in Information Theoryinformation for authors               0  0.000000              2020                Neural Networks and Applications
74173                                            Announcement of the Neural Networks Best Paper Award               0  0.000000              2020                Neural Networks and Applications

Let's drop the rows with the junk titles

In [34]:
df_20 = df_20[~(mask_exact | mask_pattern)].reset_index(drop=True)
print(f"Remaining rows: {len(df_20):,}")

Remaining rows: 293,072

In [35]:
# Discovered during EDA — IEEE index documents have unrealistic institutions_distinct_count (up to 4787) and 0 citations
# Drop IEEE index documents
ieee_index_mask = df_20['title'].str.contains('Index IEEE|Index IEEE/ACM', case=False, na=False)
print(f"IEEE index papers to drop: {ieee_index_mask.sum():,}")
df_20 = df_20[~ieee_index_mask].reset_index(drop=True)
print(f"Remaining rows: {len(df_20):,}")

IEEE index papers to drop: 19
Remaining rows: 293,053

In [36]:
# Discovered durind EDA
# Drop NeurIPS proceedings volumes — these are entire conference proceedings volumes
# misidentified by OpenAlex as individual papers, accumulating citations from all 
# papers within the volume. Not individual research papers.
neurips_mask = df_20['title'].str.contains('Advances in Neural Information Processing Systems', case=False, na=False)
print(f"NeurIPS proceedings to drop: {neurips_mask.sum()}")
df_20 = df_20[~neurips_mask].reset_index(drop=True)
print(f"Remaining rows: {len(df_20):,}")

NeurIPS proceedings to drop: 4
Remaining rows: 293,049

In [37]:
# Discovered durind EDA
# Drop CNS annual meeting abstract collections — published as single journal articles
# but contain abstracts from hundreds of presenters, accumulating their citations.
# Not individual research papers.
cns_mask = df_20['title'].str.contains('Annual Computational Neuroscience Meeting', case=False, na=False)
print(f"CNS meeting abstracts to drop: {cns_mask.sum()}")
df_20 = df_20[~cns_mask].reset_index(drop=True)
print(f"Remaining rows: {len(df_20):,}")

CNS meeting abstracts to drop: 2
Remaining rows: 293,047

In [38]:
# Discovered during EDA
# Drop non-research paper records:
# - 'Proceedings of the Second Workshop on Arabic Natural Language Processing' — workshop
#   proceedings collection misclassified as journal article, 53 authors, 0 citations
# - 'Universal Dependencies 2.7' — linguistic dataset/resource release, not a research paper
non_paper_mask = df_20['title'].isin([
    'Proceedings of the Second Workshop on Arabic Natural Language Processing',
    'Universal Dependencies 2.7'
])
print(f"Non-research paper records to drop: {non_paper_mask.sum()}")
df_20 = df_20[~non_paper_mask].reset_index(drop=True)
print(f"Remaining rows: {len(df_20):,}")

Non-research paper records to drop: 2
Remaining rows: 293,045

## Cleaning publication_type

In [39]:
print(f"publication_type ({df_20['publication_type'].nunique()} unique):")
print(df_20['publication_type'].value_counts().to_string())

publication_type (579 unique):

publication_type
journal-article                                                                                                                                                                                                                                                                    127238
proceedings-article                                                                                                                                                                                                                                                                112417
unknown                                                                                                                                                                                                                                                                             34647
text                                                                                                                                                                                                                                                                                 2396
article-journal                                                                                                                                                                                                                                                                      1851
article                                                                                                                                                                                                                                                                              1614
info:eu-repo/semantics/article                                                                                                                                                                                                                                                       1234
Conference papers                                                                                                                                                                                                                                                                    1117
info:eu-repo/semantics/conferenceObject                                                                                                                                                                                                                                               845
info:eu-repo/semantics/publishedVersion                                                                                                                                                                                                                                               829
Text                                                                                                                                                                                                                                                                                  695
Student thesis                                                                                                                                                                                                                                                                        444
Article                                                                                                                                                                                                                                                                               442
book-chapter                                                                                                                                                                                                                                                                          285
Project                                                                                                                                                                                                                                                                               232
InProceedings                                                                                                                                                                                                                                                                         232
Conference or Workshop Item                                                                                                                                                                                                                                                           222
contributionToPeriodical                                                                                                                                                                                                                                                              214
posted-content                                                                                                                                                                                                                                                                        213
info:eu-repo/semantics/other                                                                                                                                                                                                                                                          209
Conference Paper                                                                                                                                                                                                                                                                      183
project                                                                                                                                                                                                                                                                               168
Thesis                                                                                                                                                                                                                                                                                160
PeerReviewed                                                                                                                                                                                                                                                                          151
etd                                                                                                                                                                                                                                                                                   134
info:eu-repo/semantics/doctoralThesis                                                                                                                                                                                                                                                 132
info:eu-repo/semantics/lecture                                                                                                                                                                                                                                                        130
VoR                                                                                                                                                                                                                                                                                   130
conferenceObject                                                                                                                                                                                                                                                                      110
corpus                                                                                                                                                                                                                                                                                104
Journal articles                                                                                                                                                                                                                                                                       98
Conference paper                                                                                                                                                                                                                                                                       96
Final Year Project (FYP)                                                                                                                                                                                                                                                               91
conferenceobject                                                                                                                                                                                                                                                                       90
thesis                                                                                                                                                                                                                                                                                 89
info:eu-repo/semantics/conferencePaper                                                                                                                                                                                                                                                 83
master thesis                                                                                                                                                                                                                                                                          81
NonPeerReviewed                                                                                                                                                                                                                                                                        74
conference paper                                                                                                                                                                                                                                                                       67
Conference contribution                                                                                                                                                                                                                                                                66
info:eu-repo/semantics/bookPart                                                                                                                                                                                                                                                        64
H2                                                                                                                                                                                                                                                                                     57
Peer-reviewed Article                                                                                                                                                                                                                                                                  53
info:eu-repo/semantics/masterThesis                                                                                                                                                                                                                                                    52
Konferenzveröffentlichung                                                                                                                                                                                                                                                              51
info:eu-repo/semantics/conferencepaper                                                                                                                                                                                                                                                 51
Presentation                                                                                                                                                                                                                                                                           50
Journal Article                                                                                                                                                                                                                                                                        48
dissertation                                                                                                                                                                                                                                                                           46
G2 Pro gradu, diplomityö                                                                                                                                                                                                                                                               46
journal article                                                                                                                                                                                                                                                                        45
peer reviewed                                                                                                                                                                                                                                                                          43
doctoral thesis                                                                                                                                                                                                                                                                        42
doc-type:article                                                                                                                                                                                                                                                                       41
lexicalConceptualResource                                                                                                                                                                                                                                                              40
publishedVersion                                                                                                                                                                                                                                                                       40
Proceedings Paper                                                                                                                                                                                                                                                                      40
M2                                                                                                                                                                                                                                                                                     38
doc-type:conferenceObject                                                                                                                                                                                                                                                              37
Theses                                                                                                                                                                                                                                                                                 35
ProjectComponent                                                                                                                                                                                                                                                                       34
pro gradu -tutkielmat                                                                                                                                                                                                                                                                  34
info:eu-repo/semantics/preprint                                                                                                                                                                                                                                                        32
bookpart                                                                                                                                                                                                                                                                               32
doc-type:doctoralThesis                                                                                                                                                                                                                                                                31
Conference item                                                                                                                                                                                                                                                                        31
info:eu-repo/semantics/book                                                                                                                                                                                                                                                            31
Objeto de conferencia                                                                                                                                                                                                                                                                  30
report                                                                                                                                                                                                                                                                                 30
other                                                                                                                                                                                                                                                                                  28

There are 579 different publication types, which is a mess, so let's classify them into 5 groups: journal article, proceedings article, thesis, other, unknown

In [40]:
def map_publication_type(val):
    val = str(val).lower().strip()
    
    journal_keywords = ['journal', 'article', 'text', 'periodical', 'peer review', 
                        'zeitschrift', 'artículo', 'artikel', 'artykuł', 'rivista']
    conference_keywords = ['conference', 'proceedings', 'workshop', 'konferenz', 
                           'inproceedings', 'confer', 'congres', 'kongres']
    thesis_keywords = ['thesis', 'dissertation', 'doctoral', 'master', 'bachelor', 
                       'phd', 'licentiate', 'etd', 'tese', 'thèse', 'disertac']
    
    if val == 'unknown':
        return 'unknown'
    for kw in conference_keywords:
        if kw in val:
            return 'proceedings-article'
    for kw in thesis_keywords:
        if kw in val:
            return 'thesis'
    for kw in journal_keywords:
        if kw in val:
            return 'journal-article'
    return 'other'

df_20['publication_type'] = df_20['publication_type'].apply(map_publication_type)
print(df_20['publication_type'].value_counts())

publication_type
journal-article        136228
proceedings-article    116167
unknown                 34647
other                    4378
thesis                   1625
Name: count, dtype: int64

## Cleaning countries_distinct_counts

Let's see where the articles with 0 countries are concentrated

In [41]:
zeros = df_20[df_20['countries_distinct_count'] == 0]
print(f"Rows with 0 countries: {len(zeros):,}")
print(f"\nBy publication_type:")
print(zeros['publication_type'].value_counts())
print(f"\nBy publication_year:")
print(zeros['publication_year'].value_counts().sort_index())
print(f"\nBy topic_name:")
print(zeros['topic_name'].value_counts())

Rows with 0 countries: 74,428

By publication_type:
publication_type
unknown                26573
journal-article        25510
proceedings-article    17944
other                   2841
thesis                  1560
Name: count, dtype: int64

By publication_year:
publication_year
2015    7129
2016    8024
2017    7295
2018    8270
2019    9504
2020    8980
2021    6559
2022    4116
2023    4778
2024    9773
Name: count, dtype: int64

By topic_name:
topic_name
Natural Language Processing Techniques            21610
Neural Networks and Applications                  13448
Topic Modeling                                     8249
Speech Recognition and Synthesis                   6381
Anomaly Detection Techniques and Applications      5539
Sentiment Analysis and Opinion Mining              5514
Quantum Computing Algorithms and Architecture      5108
Privacy-Preserving Technologies in Data            3918
Metaheuristic Optimization Algorithms Research     2818
Evolutionary Algorithms and Applications           1843
Name: count, dtype: int64

There are 25% of articles with 0 country value, which may indicate the OpenAlex data entry issue. Let's look at this later when we pull more data about institutions

## Cleaning authors_count / institutions_distinct_count

As we noticed before, the authors count was almost reflecting the institutions count, let's see how many rows have actually equal count

In [42]:
print("authors_count == institutions_distinct_count:")
print((df_20['authors_count'] == df_20['institutions_distinct_count']).sum())
print(f"\nTotal rows: {len(df_20):,}")

print("\nCorrelation:")
print(df_20['authors_count'].corr(df_20['institutions_distinct_count']))

authors_count == institutions_distinct_count:
292960

Total rows: 293,045

Correlation:
0.861784030623429

In [43]:
293005-292918

87

Only 87 rows are different in authors count, let's see why

In [44]:
print(df_20[['authors_count', 'institutions_distinct_count']].describe())
print("\nSample where they differ:")
print(df_20[df_20['authors_count'] != df_20['institutions_distinct_count']][['authors_count', 'institutions_distinct_count']].head(20))

       authors_count  institutions_distinct_count
count  293045.000000                293045.000000
mean        3.543456                     3.560429
std         3.485310                     4.589382
min         0.000000                     0.000000
25%         2.000000                     2.000000
50%         3.000000                     3.000000
75%         4.000000                     4.000000
max       100.000000                  1229.000000

Sample where they differ:
       authors_count  institutions_distinct_count
5240             100                          101
13316            100                          142
27209            100                          131
32663            100                          227
35696            100                          108
39057            100                          115
41108            100                          114
61134            100                          121
63985            100                          132
67113            100                          165
67444            100                          165
68196            100                          111
70540            100                          104
74339            100                          194
75798            100                          150
77064            100                          251
77331            100                          109
77946            100                          114
78037            100                          131
78174            100                          115

In [45]:
print(df_20['authors_count'].value_counts().sort_index().tail(20))

authors_count
81      2
82      7
83      4
84      5
85      2
86      6
87      5
88      1
89      4
90      2
91      2
92      4
93      2
94      3
95      6
96      7
97      2
98      1
99      3
100    85
Name: count, dtype: int64

So we see that the max value in authour count is 100, while in institution count its much higher - 1229.  
This might indicate that OpenAlex set a cap on authors count at 100, or that some authors represent more institutions.  
The difference group is very small - 87 items only.

In [46]:
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    print(df_20[df_20['authors_count'] == 100][[
        'title', 'authors_count', 'institutions_distinct_count', 
        'countries_distinct_count', 'cited_by_count', 'publication_year', 
        'topic_name']].to_string())

                                                                                                                                                                                                             title  authors_count  institutions_distinct_count  countries_distinct_count  cited_by_count  publication_year                                      topic_name
5240                                                                                                                                               Constituency Parse Reranking for Morphologically Rich Languages            100                          101                         1               0              2015          Natural Language Processing Techniques
13316                                                                                                                                                              Evolving Fuzzy Models for Automated Translation            100                          142                         1               3              2017          Natural Language Processing Techniques
27209                                                                                                                       UniRule: a unified rule resource for automatic annotation in the UniProt Knowledgebase            100                          131                         4              71              2020          Natural Language Processing Techniques
32663                                                                                                                                                                                                 Book reviews            100                          227                         3               0              2020          Natural Language Processing Techniques
35696                                                                                                                                  Machine Reading Comprehension: Methods and Trends of Low Resource Languages            100                          108                         1               1              2021          Natural Language Processing Techniques
39057                                                                                         Identification and extraction of multiword expressions from Hindi &amp; Urdu language in natural language processing            100                          115                         1               3              2022          Natural Language Processing Techniques
41108                                                                                                                                                  Medical Relation Extraction from Electronic Medical Records            100                          114                         2               0              2022          Natural Language Processing Techniques
61134                                                        Real-Time Neural Signal Sensing and Spike Sorting System Using Modified Zero-Crossing Feature with Highly Efficient Data Computation and Transmission            100                          121                         1               2              2017                Neural Networks and Applications
63985                                                                                                                                                              Probability Maximization by Inner Approximation            100                          132                         0               5              2018                Neural Networks and Applications
67113                                                                                                                                                           Image Processing in Intelligent Traffic Management            100                          165                         0              29              2019                Neural Networks and Applications
67444                                                                                                                      A Fuzzy Brain Emotional Learning Classifier Design and Application in Medical Diagnosis            100                          165                         1               7              2019                Neural Networks and Applications
68196                                                                        Low Memory Footprint CNN Models for end-to-end Driving of Autonomous Ground Vehicle and Custom Adaptation to Various Road Conditions.            100                          111                         0               2              2019                Neural Networks and Applications
70540                                                                                                                                             ANN Model Identification: Parallel Big Bang Big Crunch Algorithm            100                          104                         1               0              2019                Neural Networks and Applications
74339                                                                                                                        A Study on Artificial intelligence with Machine learning and Deep Learning Techniques            100                          194                         0              20              2021                Neural Networks and Applications
75798                                                                                                                                 Convolutional Neural Network and its Applications in Artificial Intelligence            100                          150                         1               1              2021                Neural Networks and Applications
77064                                                                                                                                                  Compositional Behavioral Modeling of Analog Neural Networks            100                          251                         0               0              2021                Neural Networks and Applications
77331                                                                                                                                                                                  Stochastic Komodo Algorithm            100                          109                         1              41              2022                Neural Networks and Applications
77946                                                                                                     Predicting traffic induced noise using artificial neural network and multiple linear regression approach            100                          114                         1               5              2022                Neural Networks and Applications
78037                                                                                                                                       Point-to-set distance functions for output-constrained neural networks            100                          131                         1               3              2022                Neural Networks and Applications
78174                                                                                                                                      ER-Caps: ELU Residual Capsule Network for Complex Images Classification            100                          115                         1               3              2022                Neural Networks and Applications
79341                                                                                                 Recurrent neural network with $L_{1/2}$ regularization for regression and multiclass classification problems            100                          103                         1               0              2022                Neural Networks and Applications
80474                                                                                                                                               Data Distinguisher Module Implementation using CMOS Techniques            100                          262                         0               2              2023                Neural Networks and Applications
80576                                                                                                                         EEG-Based Emotion Classification: A Biologically Informed Channel Selection Approach            100                          153                         2               2              2023                Neural Networks and Applications
80916                                                                                    An Enhancement of Tree-Structured Deep Learning Classification Through Semantic Enabled Frequency Aware Data Augmentation            100                          107                         0               1              2023                Neural Networks and Applications
80920                                                                                                            Guided Co-operative Waderhunt Neural Network for Measuring the Temperature of Visible Heat Source            100                          112                         1               1              2023                Neural Networks and Applications
81045                                                                                                                                 DEEP LEARNING APPROACHES FOR ANOMALY DETECTION IN INTERNET OF THINGS SYSTEMS            100                          194                         0               0              2023                Neural Networks and Applications
81344                                                                                                                                                                               Semi-implicit back propagation            100                          113                         1               0              2023                Neural Networks and Applications
106345                                                                                                                                                  Top approaches to abstractive text summarization: A survey            100                          108                         1               1              2020                                  Topic Modeling
114170                                                                                                                                                                Event-related microblog retrieval in Turkish            100                          166                         1               0              2021                                  Topic Modeling
114370                                                                                                                                             BLOOM: A 176B-Parameter Open-Access Multilingual Language Model            100                          394                         0             277              2022                                  Topic Modeling
127161                                                                                                                 Large-Scale Knowledge Synthesis and Complex Information Retrieval from Biomedical Documents            100                          164                         0               1              2023                                  Topic Modeling
135791                                                                                NewsZoom (focus on the important): Text summarization of News Articles based on named entity recognition using Spacy library            100                          106                         0               0              2024                                  Topic Modeling
142861                                                                                                                        Whispered Speech Recognition using Hidden Markov Models and Support Vector Machines             100                          125                         2              10              2018                Speech Recognition and Synthesis
146240                                                                                             Efficient Search Mechanism from Large Scale Corpora for Domain-Specific Language Modeling in Speech Recognition            100                          107                         2               0              2019                Speech Recognition and Synthesis
154670                                                                                             A Comparative Analysis of Convolutional Neural Network and Recurrent Neural Network for Voice Disease Detection            100                          143                         0               0              2023                Speech Recognition and Synthesis
161188                                                                                                                   A Survey Paper on Extraction of Web Services for Effective User Review Sentiment Analysis            100                          139                         0               0              2016           Sentiment Analysis and Opinion Mining
166598                                                                                                                                      Machine Learning Techniques for Sentiment Analysis of Indian Languages            100                          103                         0               4              2019           Sentiment Analysis and Opinion Mining
168305                                                                                                                 A Combination of Lexicon and Machine Learning Approaches for Sentiment Analysis on Facebook            100                          113                         2              22              2020           Sentiment Analysis and Opinion Mining
172701                                                                                                    A Survey: Sentimental Analysis on Product Reviews Using (MLT) Machine Learning Techniques and Approaches            100                          204                         0               2              2021           Sentiment Analysis and Opinion Mining
173485                                                                                      Sentiment Analysis of Roman-Urdu Tweets about Covid-19 Using Machine Learning Approach: A Systematic Literature Review            100                          145                         0               0              2021           Sentiment Analysis and Opinion Mining
174369                                                                                                            A Joint Multi-task Architecture for Document-level Aspect-based Sentiment Analysis in Vietnamese            100                          134                         0               9              2022           Sentiment Analysis and Opinion Mining
174642                                    Natural Language Processing of Movie Reviews to Detect the Sentiments using Novel Bidirectional Encoder Representation-BERT for Transformers over Support Vector Machine            100                          126                         1              10              2022           Sentiment Analysis and Opinion Mining
176123                                                Analysing the Sentiments in e-newspaper Contents using Novel Bidirectional Encoder Representation for Transformation - BERT over Linear Regression Algorithm            100                          125                         1               1              2022           Sentiment Analysis and Opinion Mining
176387                                                                                                                                       Classification of Twitter COVID Tweets Using Deep CNN-SLSTM Technique            100                          106                         1               0              2022           Sentiment Analysis and Opinion Mining
176518                                  Improving the Efficiency in Identification of Sentiments of COVID Patients over Online Social Networks using Novel Naive Bayes Algorithm Comparing Random Forest Algorithm            100                          185                         2               0              2022           Sentiment Analysis and Opinion Mining
178151                                                                                                              Improvisation in opinion mining using data preprocessing techniques based on consumer’s review            100                          108                         1               4              2023           Sentiment Analysis and Opinion Mining
179810                                                                                                                                                       Judgemental Analysis of Data and Prediction Using ANN            100                          113                         1               0              2023           Sentiment Analysis and Opinion Mining
180129                                                                                                                          Arabic Opinion Mining System for E-Services Based On Ontology and Machine Learning            100                          119                         1               0              2023           Sentiment Analysis and Opinion Mining
182845                                                                                                             Objectivity-Subjectivity Detection to Boost Sentiment Analysis Accuracy: An Approach using BERT            100                          103                         1               0              2024           Sentiment Analysis and Opinion Mining
198664                                                                                                                            Disruption prediction with artificial intelligence techniques in tokamak plasmas            100                         1229                        30              80              2022   Anomaly Detection Techniques and Applications
199658                                                                                                                                    Anomaly detection in surveillance videos based on H265 and deep learning            100                          132                         1              15              2022   Anomaly Detection Techniques and Applications
201670                                                                                                                                                                     DASC/PiCom/CBDCom/CyberSciTech 2022 TOC            100                          189                         0               0              2022   Anomaly Detection Techniques and Applications
204801                                                                                                           DETECTING ABNORMAL BEHAVIOUR OF USERS OF DATA PROCESSING CENTRES OF HIGHER EDUCATION INSTITUTIONS            100                          119                         1               1              2023   Anomaly Detection Techniques and Applications
205478                                                                                                                     HOCD: Overlapping Community Detection based on Hypergraph Convolutional Neural Networks            100                          138                         1               0              2023   Anomaly Detection Techniques and Applications

In [47]:
for idx in [32662, 201653, 198648, 176507, 28430]:
    print(f"\nRow {idx}:")
    print(df_20.loc[idx, 'id'])

Row 32662:
https://openalex.org/W4212932563

Row 201653:
https://openalex.org/W4311213197

Row 198648:
https://openalex.org/W4213101961

Row 176507:
https://openalex.org/W4312383299

Row 28430:
https://openalex.org/W3176687562

After checking the difference between authors_count and institutions_distinct_count through the real links, it became clear that there is indeed a cap on authors_count and institutions_distinct_count represent the actual authors count.
Therefore we will drop the authors_count column and rename `institutions_distinct_count` into `authorship_count`

In [48]:
df_20 = df_20.drop(columns=['authors_count'])

In [49]:
df_20 = df_20.rename(columns={'institutions_distinct_count': 'authorship_count'})
df_20.columns.tolist()

['id',
 'title',
 'publication_year',
 'language',
 'cited_by_count',
 'referenced_works_count',
 'fwci',
 'authorship_count',
 'countries_distinct_count',
 'publication_type',
 'is_oa',
 'oa_status',
 'citation_top_1_percent',
 'citation_top_10_percent',
 'keyword_count',
 'primary_topic_score',
 'first_year_citations',
 'topic_id',
 'topic_name']

## Cleaning referenced_works_count

In [50]:
zeros_ref = df_20[df_20['referenced_works_count'] == 0]
print(f"Rows with 0 references: {len(zeros_ref):,}")
print(f"\nBy publication_type:")
print(zeros_ref['publication_type'].value_counts())
print(f"\nBy publication_year:")
print(zeros_ref['publication_year'].value_counts().sort_index())
print(f"\nBy topic_name:")
print(zeros_ref['topic_name'].value_counts())

Rows with 0 references: 72,778

By publication_type:

publication_type
journal-article        25583
unknown                25239
proceedings-article    17368
other                   3294
thesis                  1294
Name: count, dtype: int64

By publication_year:
publication_year
2015     6128
2016     6991
2017     6895
2018     8211
2019     8824
2020     8184
2021     6135
2022     4341
2023     4577
2024    12492
Name: count, dtype: int64

By topic_name:
topic_name
Natural Language Processing Techniques            21533
Neural Networks and Applications                  16022
Topic Modeling                                     5733
Anomaly Detection Techniques and Applications      5504
Speech Recognition and Synthesis                   5478
Quantum Computing Algorithms and Architecture      5070
Sentiment Analysis and Opinion Mining              4313
Privacy-Preserving Technologies in Data            4029
Metaheuristic Optimization Algorithms Research     2970
Evolutionary Algorithms and Applications           2126
Name: count, dtype: int64

There are 25% of articles with 0 referenced_works value, which may indicate the OpenAlex data entry issue. Let's look at this later when we pull more data

## Save cleaned csv

In [51]:
df_20.to_csv('../data/OpenAlex/openalex_ai_papers_cleaned.csv', index=False)
print(f"Saved: {df_20.shape}")

Saved: (293045, 19)

In [52]:
df_clean = pd.read_csv("../data/OpenAlex/openalex_ai_papers_cleaned.csv")
df_clean.head()

,id,title,publication_year,language,cited_by_count,referenced_works_count,fwci,authorship_count,countries_distinct_count,publication_type,is_oa,oa_status,citation_top_1_percent,citation_top_10_percent,keyword_count,primary_topic_score,first_year_citations,topic_id,topic_name
0,https://openalex.org/W1902237438,Effective Approaches to Attention-based Neural...,2015,en,8508,20,633.3691,3,1,proceedings-article,1,gold,1,1,7,0.9999,155,T10181,Natural Language Processing Techniques
1,https://openalex.org/W658020064,From Word Embeddings To Document Distances,2015,en,1518,47,164.8113,4,1,other,0,closed,1,1,11,0.9996,61,T10181,Natural Language Processing Techniques
2,https://openalex.org/W2251135946,Distant Supervision for Relation Extraction vi...,2015,en,1200,31,87.4904,4,1,proceedings-article,1,gold,1,1,11,0.9992,17,T10181,Natural Language Processing Techniques
3,https://openalex.org/W1491002046,An Introduction to Recursive Partitioning Usin...,2015,en,1030,7,105.2714,2,0,unknown,0,closed,1,1,14,0.9880,54,T10181,Natural Language Processing Techniques
4,https://openalex.org/W2250342921,chrF: character n-gram F-score for automatic M...,2015,en,935,10,36.6006,1,1,proceedings-article,1,gold,1,1,8,1.0000,14,T10181,Natural Language Processing Techniques